# Generated by Django 5.1.6 on 2025-02-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('und', models.CharField(max_length=10, verbose_name='Unidade')),
                ('grupo', models.CharField(choices=[('B', 'Banda'), ('R', 'Reparo'), ('O', 'Outros')], default='O', max_length=1)),
                ('subgrupo', models.CharField(max_length=100)),
                ('tipo_tracao', models.CharField(choices=[('D', 'Direcional'), ('T', 'Tração'), ('M', 'Misto')], max_length=1, verbose_name='Tipo de Tração')),
                ('cod_bandag', models.CharField(max_length=50, verbose_name='Código Bandag')),
                ('tamanho', models.IntegerField(null=True, verbose_name='Tamanho')),
                ('categoria', models.CharField(choices=[('N', 'Novo'), ('R', 'Recapado'), ('C', 'Carcaça')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['descricao'],
            },
        ),
    ]
