# Generated by Django 5.1.6 on 2025-02-20 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('produto', '0001_initial'),
        ('tamanho', '0001_initial'),
        ('vendedor', '0002_vendedor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('numero_apanha', models.CharField(max_length=20, unique=True)),
                ('forma_pagamento', models.CharField(choices=[('AV', 'À Vista'), ('AP', 'A Prazo'), ('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('PIX', 'PIX')], default='AV', max_length=3)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendedor.vendedor')),
            ],
            options={
                'verbose_name': 'Coleta',
                'verbose_name_plural': 'Coletas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='PneusColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=50)),
                ('fogo', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montado', models.BooleanField(default=False)),
                ('coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pneus', to='coleta.coleta')),
                ('desenho', models.ForeignKey(limit_choices_to={'grupo': 'B'}, on_delete=django.db.models.deletion.PROTECT, to='produto.produto')),
                ('tamanho', models.ForeignKey(limit_choices_to={'status': 'A'}, on_delete=django.db.models.deletion.PROTECT, to='tamanho.tamanho')),
            ],
            options={
                'verbose_name': 'Pneu da Coleta',
                'verbose_name_plural': 'Pneus da Coleta',
                'ordering': ['serie'],
            },
        ),
    ]
