# Generated by Django 5.1.6 on 2025-02-21 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0001_initial'),
        ('fabricante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneuscoleta',
            name='fabricante',
            field=models.ForeignKey(limit_choices_to={'status': 'A'}, on_delete=django.db.models.deletion.PROTECT, to='fabricante.fabricante'),
        ),
    ]
