# Generated by Django 5.1.6 on 2025-02-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0003_pneuscoleta_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneuscoleta',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
