# Generated by Django 5.1.6 on 2025-02-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
